server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connection-timeout: 5000
          timeout: 3000
          write timeout: 5000
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 1046526186364-1ff4ii7rmelqo7q7d0dqjsum4a7rgkg0.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile

          facebook:
            clientId: 713999016373246
            clientSecret: f442c0143cb94e65bd83d402ac5835bf
            scope:
              - email
              - public_profile


